import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

let currentPath = '';

function filterOpenApiSidebarItems(item) {
  // Remove Introduction items
  if (item.type === 'doc' && !item.className) {
    return false;
  }

  if (!item.key) { 
    item.key = currentPath + item.label;
  }

  if (item.type === 'category' && item.items) {
    // Change items with only one item
    if (item.items.length === 2 && item.items[0].type === 'doc' && !item.items[0].className &&
      item.items[1].type === 'category' && item.items[1].label === item.label) {
      item.items = item.items[1].items;
    } else {
      let prevPath = currentPath;
      currentPath += item.label + '.';
      item.items = item.items.filter(filterOpenApiSidebarItems);
      currentPath = prevPath;
    }
  }

  return true;
}

function getSidebarItems(sidbarPath) {
  currentPath = '';
  return require(sidbarPath).filter(filterOpenApiSidebarItems);
}

const sidebars: SidebarsConfig = {
  docsDocs: [{type: 'autogenerated', dirName: 'docs/docs-api'},],
  docsOffice: [{type: 'autogenerated', dirName: 'docs/office-api'},],
  docsPlugins: [{type: 'autogenerated', dirName: 'docs/plugins'},],
  docsMacros: [{type: 'autogenerated', dirName: 'docs/macros'},],
  docsAI: [{type: 'autogenerated', dirName: 'docs/ai'},],
  docsBuilder: [{type: 'autogenerated', dirName: 'docs/document-builder'},],
  docsDesktop: [{type: 'autogenerated', dirName: 'docs/desktop-editors'},],

  docspaceJSSdk: [
    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/javascript-sdk/get-started'}],
    },
    {
      type: "category",
      label: "Embedding modes",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/javascript-sdk/embedding-modes'}],
    },
    {
      type: "category",
      label: "SDK usage",
      collapsed: false,
      items: [...require('./site/docspace/javascript-sdk/usage-sdk/typedoc-sidebar.cjs')],
    },
    {
      type: "category",
      label: "Samples",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/javascript-sdk/samples'}],
    },
  ],
  docspacePlugins: [{type: 'autogenerated', dirName: 'docspace/plugins-sdk'},],
  docspaceApiBackend: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: getSidebarItems("./site/docspace/api-backend/usage-api/sidebar.ts"),
    },
    {
      type: "category",
      label: "Samples",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/samples'}],
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/more-information'}],
    },
  ],
  docspaceMCPServer: [
    {
      type: "autogenerated",
      dirName: 'docspace/mcp-server',
    },
  ],
  workspaceBackend: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/api-backend/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: getSidebarItems("./site/workspace/api-backend/usage-api/sidebar.ts"),
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/api-backend/more-information'}],
    },
  ],
  workspaceHosting: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/for-hosting-providers/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: getSidebarItems("./site/workspace/for-hosting-providers/usage-api/sidebar.ts"),
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/for-hosting-providers/more-information'}],
    },
  ],
};

export default sidebars;
