import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

let category_keys = {};
const filterOpenApiSidebarItems = (item) => {
  // Remove Introduction items
  if (item.type === 'doc' && !item.className) {
    return false;
  }

  if (item.type === 'category' && item.items) {
    // Set unique key for item. https://docusaurus.io/docs/sidebar#passing-unique-key
    if (!item.key) {
      let ikey = item.label.replace(' ', '-');
      if (!category_keys[item.label])
        category_keys[item.label] = 1;
      else
        category_keys[item.label] += 1;
      item.key = ikey + '-' + category_keys[item.label];
    }
    // Change items with only one item
    if (item.items.length === 2 && item.items[0].type === 'doc' && !item.items[0].className &&
      item.items[1].type === 'category' && item.items[1].label === item.label) {
      item.items = item.items[1].items;
    } else {
      item.items = item.items.filter(filterOpenApiSidebarItems);
    }
  }

  return true;
};

const sidebars: SidebarsConfig = {
  docspaceJSSdk: [{type: 'autogenerated', dirName: 'docspace/javascript-sdk'},],
  docspacePlugins: [{type: 'autogenerated', dirName: 'docspace/plugins-sdk'},],
  docspaceApiBackend: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: require("./site/docspace/api-backend/usage-api/sidebar.ts")
        .filter(filterOpenApiSidebarItems),
    },
    {
      type: "category",
      label: "Samples",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/samples'}],
      link: {type: 'doc', id: 'docspace/api-backend/samples/samples'},
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/more-information'}],
    },
  ],
  docspaceHosting: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/for-hosting-providers/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: require("./site/docspace/for-hosting-providers/usage-api/sidebar.ts")
        .filter(filterOpenApiSidebarItems),
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'docspace/for-hosting-providers/more-information'}],
    },
  ],

  docsDocs: [{type: 'autogenerated', dirName: 'docs/docs-api'},],
  docsOffice: [{type: 'autogenerated', dirName: 'docs/office-api'},],
  docsMacros: [{type: 'autogenerated', dirName: 'docs/plugin-and-macros'},],
  docsBuilder: [{type: 'autogenerated', dirName: 'docs/document-builder'},],
  docsDesktop: [{type: 'autogenerated', dirName: 'docs/desktop-editors'},],

  workspaceBackend: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/api-backend/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: require("./site/workspace/api-backend/usage-api/sidebar.ts")
        .filter(filterOpenApiSidebarItems),
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/api-backend/more-information'}],
    },
  ],
  workspaceHosting: [
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/for-hosting-providers/get-started'}],
    },
    {
      type: "category",
      label: "API usage",
      collapsed: false,
      items: require("./site/workspace/for-hosting-providers/usage-api/sidebar.ts")
        .filter(filterOpenApiSidebarItems),
    },
    {
      type: "category",
      label: "More information",
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'workspace/for-hosting-providers/more-information'}],
    },
  ],
  samples: [{type: 'autogenerated', dirName: 'samples'},],
};

export default sidebars;
