import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Files",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "openapi/docspace/api-backend/usage-api/asc-files",
        },
        {
          type: "category",
          label: "Files",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/save-editing-from-form",
              label: "Save file edits",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/start-edit",
              label: "Start file editing",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/start-filling",
              label: "Starts filling",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/track-edit-file",
              label: "Track file editing",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/open-edit",
              label: "Open a file",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-presigned-file-uri",
              label: "Get file download link asynchronously",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-reference-data",
              label: "Get reference data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/protect-users",
              label: "Get users with the access to the protected file",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-history",
              label: "Get file history",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-history",
              label: "Change version history",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-file-version-info",
              label: "Get file versions",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-presigned-uri",
              label: "Get file download link",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/is-form-pdf",
              label: "Check the PDF file",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/copy-file-as",
              label: "Copy a file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-file",
              label: "Create a file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-html-file",
              label: "Create an HTML file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-text-file",
              label: "Create a txt file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-file",
              label: "Delete a file",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-file-info",
              label: "Get file information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/update-file",
              label: "Update a file",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-fill-result",
              label: "Gets fill result",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-edit-diff-url",
              label: "Get changes URL",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-edit-history",
              label: "Get version history",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/lock-file",
              label: "Lock a file",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/restore-version",
              label: "Restore a file version",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-primary-external-link",
              label: "Create primary external link",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-file-primary-external-link",
              label: "Get primary external link",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-order",
              label: "Sets order of a file with ID specified in the request",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-order-1",
              label: "Sets order",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-links",
              label: "Get file external links",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-external-link",
              label: "Set an external link",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/save-as-pdf",
              label: "Save as pdf",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-file-my-documents",
              label: "Create a file in the 'My documents' section",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-html-file-in-my",
              label: "Create an HTML file in the 'My documents' section",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-text-file-in-my",
              label: "Create a text file in the 'My documents' section",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-thumbnails",
              label: "Create thumbnails",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/check-fill-form-draft",
              label: "Check the form draft",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/add-templates",
              label: "Add template files",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-templates",
              label: "Delete template files",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-recent",
              label: "Delete recent files",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-edit-session",
              label: "Create the editing session",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Folders",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-history-1",
              label: "Get folder history",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-folder",
              label: "Create a folder",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-folder",
              label: "Delete a folder",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-folder-info",
              label: "Get folder information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/rename-folder",
              label: "Rename a folder",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-file-order",
              label: "Sets file order in the folder with ID specified in the request",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-folder",
              label: "Get a folder by ID",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-folder-path",
              label: "Get the folder path",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-folders",
              label: "Get subfolders",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-new-items",
              label: "Get new folder items",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-files-used-space",
              label: "Get used space of files",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-folder-primary-external-link",
              label: "Get primary external link",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-my-folder",
              label: "Get the 'My documents' section",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-privacy-folder",
              label: "Get the 'Private Room' section",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-root-folders",
              label: "Get filtered sections",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-trash-folder",
              label: "Get the 'Trash' section",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/check-upload",
              label: "Checks upload",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/insert-file",
              label: "Insert a file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/upload-file",
              label: "Upload a file",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/insert-file-to-my-from-body",
              label: "Insert a file to the 'My documents' section",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/upload-file-to-my",
              label: "Upload a file to the 'My documents' section",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Operations",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/check-conversion",
              label: "Get conversion status",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/start-conversion",
              label: "Start file conversion",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/update-comment",
              label: "Update a comment",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/bulk-download",
              label: "Bulk download",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/copy-batch-items",
              label: "Copy to a folder",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-batch-items",
              label: "Delete files and folders",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/empty-trash",
              label: "Empty the 'Trash' folder",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-operation-statuses",
              label: "Get active operations",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/mark-as-read",
              label: "Mark as read",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/move-batch-items",
              label: "Move to a folder",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/move-or-copy-batch-check",
              label: "Check files and folders for conflicts",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/duplicate-batch-items",
              label: "Duplicates all the selected files and folders",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/move-or-copy-dest-folder-check",
              label: "Moves or copies",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/terminate-tasks",
              label: "Finish active operations",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-upload-session",
              label: "Chunked upload",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Quota",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/update-rooms-quota",
              label: "Change a room quota limit",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/reset-room-quota",
              label: "Reset a room quota limit",
              className: "api-method put",
            },
          ],
        },
        {
          type: "category",
          label: "Rooms",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-room",
              label: "Create a room",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-rooms-folder",
              label: "Get rooms",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-room-info",
              label: "Get room information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/update-room",
              label: "Rename a room",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-room",
              label: "Remove a room",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/archive-room",
              label: "Archive a room",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/unarchive-room",
              label: "Unarchive a room",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-room-security",
              label: "Set room access rights",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-room-security-info",
              label: "Get room access rights",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-link",
              label: "Set an external or invitation link",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-room-links",
              label: "Get room links",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-rooms-primary-external-link",
              label: "Get primary external link",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/add-tags",
              label: "Add room tags",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-tags",
              label: "Remove room tags",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-room-logo",
              label: "Create a room logo",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-room-logo",
              label: "Remove a room logo",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-room-cover",
              label: "Changes room cover",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-covers",
              label: "Gets covers",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/pin-room",
              label: "Pin a room",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/unpin-room",
              label: "Unpin a room",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/resend-email-invitations",
              label: "Resend room invitations",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/reorder",
              label: "Reorders to a room with ID specified in the request",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-new-items-1",
              label: "Get new room items",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-room-third-party",
              label: "Create a third-party room",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/create-tag",
              label: "Create a tag",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-tags-info",
              label: "Get tags",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-custom-tags",
              label: "Delete tags",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/upload-room-logo",
              label: "Upload an image for room logo",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/start-room-index-export",
              label: "Starts room index export",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-room-index-export",
              label: "Gets room index export",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/terminate-room-index-export",
              label: "Terminates room index export",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-rooms-new-items",
              label: "Gets room new items",
              className: "api-method get",
            },
          ],
        },
        {
          type: "category",
          label: "Settings",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/check-doc-service-url",
              label: "Check the document service URL",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-access-to-thirdparty",
              label: "Change the third-party settings access",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-delete-confirm",
              label: "Confirm the file deletion",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-download-zip-from-body",
              label: "Change the archive format (using body parameters)",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/external-share",
              label: "Change the external sharing ability",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/external-share-social-media",
              label: "Change the external sharing ability on social networks",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/forcesave",
              label: "Change the forcasaving ability",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-files-settings",
              label: "Get file settings",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-module",
              label: "Get the Documents information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/is-available-privacy-room-settings",
              label: "Check the Private Room availability",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/store-forcesave",
              label: "Change the ability to store the forcesaved files",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/store-original",
              label: "Change the ability to upload original formats",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/keep-new-file-name",
              label: "Ask a new file name",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/display-file-extension",
              label: "Display a file extension",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/update-if-exist",
              label: "Update a file version if it exists",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-automatically-clean-up",
              label: "Get the trash bin auto-clearing setting",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-automatically-clean-up",
              label: "Update the trash bin auto-clearing setting",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/change-default-access-rights",
              label: "Change the default access rights",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/set-open-editor-in-same-tab",
              label: "Open document in same browser tab",
              className: "api-method put",
            },
          ],
        },
        {
          type: "category",
          label: "Third-party integration",
          items: [
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-third-party-accounts",
              label: "Get third-party accounts",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/save-third-party",
              label: "Save a third-party account",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/capabilities",
              label: "Get providers",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/delete-third-party",
              label: "Remove a third-party account",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-common-third-party-folders",
              label: "Get common third-party services",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-backup-third-party-account",
              label: "Get a third-party account backup",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/save-third-party-backup",
              label: "Save a third-party account backup",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "openapi/docspace/api-backend/usage-api/get-all-providers",
              label: "Get all providers",
              className: "api-method get",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
