// todo: normalize naming of eleventy, remark, and other plugins.

import {eleventyClean} from "@onlyoffice/eleventy-clean"
import {eleventyEsbuild} from "@onlyoffice/eleventy-esbuild"
import {eleventyHtmlMinifierTerser} from "@onlyoffice/eleventy-html-minifier-terser"
import {eleventyLightningcss} from "@onlyoffice/eleventy-lightningcss"
import {eleventyPagefind} from "@onlyoffice/eleventy-pagefind"
import {eleventyStarryNight} from "@onlyoffice/eleventy-starry-night"
import {type UserConfig} from "@onlyoffice/eleventy-types"
import {eleventyYAML} from "@onlyoffice/eleventy-yaml"
import {isBuild, isPreview} from "@onlyoffice/site-env"
import {markupPlugin} from "./config/markup.ts"
import {navigationPlugin} from "./config/navigation.ts"
import {previewPlugin} from "./config/preview.ts"
import {staticPlugin} from "./config/static.ts"

import {eleventyPlugin as sitemapPlugin} from "./config/sitemap.ts"

function config(uc: UserConfig): unknown {
  const minify = isBuild() || isPreview()

  uc.addPlugin(eleventyClean)
  uc.addPlugin(staticPlugin)
  uc.addPlugin(markupPlugin)

  uc.addPlugin(eleventyLightningcss, {
    filename: "assets/main.css",
    minify
  })

  uc.addPlugin(eleventyEsbuild, {
    input: "assets/main.ts",
    target: "assets",
    minify,
    rename() {
      return "main.js"
    }
  })

  uc.addPlugin(eleventyHtmlMinifierTerser, {
    minify,
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    decodeEntities: true,
    includeAutoGeneratedTags: false,
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeRedundantAttributes: true,
    sortAttributes: true
  })

  uc.addPlugin(navigationPlugin)
  uc.addPlugin(eleventyStarryNight)
  uc.addPlugin(previewPlugin)

  uc.addPlugin(eleventyYAML)
  uc.addPlugin(sitemapPlugin)

  uc.addPlugin(eleventyPagefind)

  return {
    dir: {
      data: "data",
      includes: "../components",
      input: "pages",
      layouts: "../layouts",
      output: "dist"
    }
  }
}

// Eleventy does not understand the default export.
// eslint-disable-next-line unicorn/prefer-module
module.exports = config
