import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Basic samples",
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/samples/basic-samples'}],
    },
    {
      type: "category",
      label: "Integration samples",
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'docspace/api-backend/samples/integration-samples'}],
    },
  ],
}

export default sidebar.apisidebar;
