builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
oParagraph.AddText("ONLYOFFICE Document Builder");
var oRange = oDocument.GetRange(0, 9);
oRange.AddBookmark("Bookmark");
oParagraph.AddLineBreak();
oParagraph.AddText("A bookmark was added to the 'ONLYOFFICE' range.");
builder.SaveFile("docx", "AddBookmark.docx");
builder.CloseFile();
