builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oTableStyle = oDocument.CreateStyle("CustomTableStyle", "table");
oTableStyle.SetBasedOn(oDocument.GetStyle("Bordered"));
var oTable = Api.CreateTable(3, 3);
oTable.SetStyle(oTableStyle);
var oRow = oTable.GetRow(0);
oRow.GetCell(0).GetContent().GetElement(0).AddText("Second row");
oTable.SetWidth("percent", 100);
oRow.AddRows(1, true);
oDocument.Push(oTable);
builder.SaveFile("docx", "AddRows.docx");
builder.CloseFile();
