import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "openapi/docSpace/API Backend/Usage API/asc-files",
    },
    {
      type: "category",
      label: "Files / Files",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-editing-from-form",
          label: "Save file edits",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-edit",
          label: "Start file editing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-filling",
          label: "Starts filling",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/track-edit-file",
          label: "Track file editing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/open-edit",
          label: "Open a file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-presigned-file-uri",
          label: "Get file download link asynchronously",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-reference-data",
          label: "Get reference data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/protect-users",
          label: "Get users with the access to the protected file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-file-history",
          label: "Get file history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-history",
          label: "Change version history",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-file-version-info",
          label: "Get file versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-presigned-uri",
          label: "Get file download link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/is-form-pdf",
          label: "Check the PDF file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/copy-file-as",
          label: "Copy a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-file",
          label: "Create a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-html-file",
          label: "Create an HTML file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-text-file",
          label: "Create a txt file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-file",
          label: "Delete a file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-file-info",
          label: "Get file information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-file",
          label: "Update a file",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-fill-result",
          label: "Gets fill result",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-edit-diff-url",
          label: "Get changes URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-edit-history",
          label: "Get version history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/lock-file",
          label: "Lock a file",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/restore-version",
          label: "Restore a file version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-file-primary-external-link",
          label: "Get primary external link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-order",
          label: "Sets order of a file with ID specified in the request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-links",
          label: "Get file external links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-external-link",
          label: "Set an external link",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-as-pdf",
          label: "Save as pdf",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-file-my-documents",
          label: "Create a file in the 'My documents' section",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-html-file-in-my",
          label: "Create an HTML file in the 'My documents' section",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-text-file-in-my",
          label: "Create a text file in the 'My documents' section",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-thumbnails",
          label: "Create thumbnails",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/check-fill-form-draft",
          label: "Check the form draft",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-templates",
          label: "Add template files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-templates",
          label: "Delete template files",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-recent",
          label: "Delete recent files",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-edit-session",
          label: "Create the editing session",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Folders",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-history",
          label: "Get folder history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-folder",
          label: "Create a folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-folder",
          label: "Delete a folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-folder-info",
          label: "Get folder information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/rename-folder",
          label: "Rename a folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-file-order",
          label: "Sets file order in the folder with ID specified in the request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-folder",
          label: "Get a folder by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-folder-path",
          label: "Get the folder path",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-folders",
          label: "Get subfolders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-new-items",
          label: "Get new folder items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-files-used-space",
          label: "Get used space of files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-folder-primary-external-link",
          label: "Get primary external link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-my-folder",
          label: "Get the 'My documents' section",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-privacy-folder",
          label: "Get the 'Private Room' section",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-root-folders",
          label: "Get filtered sections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-trash-folder",
          label: "Get the 'Trash' section",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/check-upload",
          label: "Checks upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/insert-file",
          label: "Insert a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-file",
          label: "Upload a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/insert-file-to-my-from-body",
          label: "Insert a file to the 'My documents' section",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-file-to-my",
          label: "Upload a file to the 'My documents' section",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Operations",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/check-conversion",
          label: "Get conversion status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-conversion",
          label: "Start file conversion",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-comment",
          label: "Update a comment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/bulk-download",
          label: "Bulk download",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/copy-batch-items",
          label: "Copy to a folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-batch-items",
          label: "Delete files and folders",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/empty-trash",
          label: "Empty the 'Trash' folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-operation-statuses",
          label: "Get active operations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/mark-as-read",
          label: "Mark as read",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/move-batch-items",
          label: "Move to a folder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/move-or-copy-batch-check",
          label: "Check files and folders for conflicts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/duplicate-batch-items",
          label: "Duplicates all the selected files and folders",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/move-or-copy-dest-folder-check",
          label: "Moves or copies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/terminate-tasks",
          label: "Finish active operations",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-upload-session",
          label: "Chunked upload",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Quota",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-rooms-quota",
          label: "Change a room quota limit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-room-quota",
          label: "Reset a room quota limit",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Rooms",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-room",
          label: "Create a room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-rooms-folder",
          label: "Get rooms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-room-info",
          label: "Get room information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-room",
          label: "Rename a room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-room",
          label: "Remove a room",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/archive-room",
          label: "Archive a room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/unarchive-room",
          label: "Unarchive a room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-room-security",
          label: "Set room access rights",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-room-security-info",
          label: "Get room access rights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-link",
          label: "Set an external or invitation link",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-room-links",
          label: "Get room links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-rooms-primary-external-link",
          label: "Get primary external link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-tags",
          label: "Add room tags",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-tags",
          label: "Remove room tags",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-room-logo",
          label: "Create a room logo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-room-logo",
          label: "Remove a room logo",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/pin-room",
          label: "Pin a room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/unpin-room",
          label: "Unpin a room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/resend-email-invitations",
          label: "Resend room invitations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-settings",
          label: "Updates settings to a room with ID specified in the request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reorder",
          label: "Reorders to a room with ID specified in the request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-room-third-party",
          label: "Create a third-party room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-tag",
          label: "Create a tag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-tags-info",
          label: "Get tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-custom-tags",
          label: "Delete tags",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-room-logo",
          label: "Upload an image for room logo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-room-index-export",
          label: "Starts room index export",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-room-index-export",
          label: "Gets room index export",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/terminate-room-index-export",
          label: "Terminates room index export",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/check-doc-service-url",
          label: "Check the document service URL",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-access-to-thirdparty",
          label: "Change the third-party settings access",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-delete-confirm",
          label: "Confirm the file deletion",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-download-zip-from-body",
          label: "Change the archive format (using body parameters)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/external-share",
          label: "Change the external sharing ability",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/external-share-social-media",
          label: "Change the external sharing ability on social networks",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/forcesave",
          label: "Change the forcasaving ability",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-files-settings",
          label: "Get file settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-module",
          label: "Get the Documents information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/is-available-privacy-room-settings",
          label: "Check the Private Room availability",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/store-forcesave",
          label: "Change the ability to store the forcesaved files",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/store-original",
          label: "Change the ability to upload original formats",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/keep-new-file-name",
          label: "Ask a new file name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-if-exist",
          label: "Update a file version if it exists",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-automatically-clean-up",
          label: "Get the trash bin auto-clearing setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-automatically-clean-up",
          label: "Update the trash bin auto-clearing setting",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-default-access-rights",
          label: "Change the default access rights",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-open-editor-in-same-tab",
          label: "Open document in same browser tab",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Files / Third-party integration",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-third-party-accounts",
          label: "Get third-party accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-third-party",
          label: "Save a third-party account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/capabilities",
          label: "Get providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-third-party",
          label: "Remove a third-party account",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-common-third-party-folders",
          label: "Get common third-party services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-backup-third-party-account",
          label: "Get a third-party account backup",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-third-party-backup",
          label: "Save a third-party account backup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-providers",
          label: "Get all providers",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Backup",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-backup-schedule",
          label: "Get the backup schedule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-backup-schedule",
          label: "Create the backup schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-backup-schedule",
          label: "Delete the backup schedule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-backup",
          label: "Start the backup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-backup-progress",
          label: "Get the backup progress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-backup-history",
          label: "Get the backup history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-backup",
          label: "Delete the backup",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-backup-history",
          label: "Delete the backup history",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-backup-restore",
          label: "Start the restoring process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-restore-progress",
          label: "Get the restoring progress",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Group",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-groups",
          label: "Get groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-group",
          label: "Add a new group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-group",
          label: "Get a group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-group",
          label: "Update a group",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-group",
          label: "Delete a group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-by-user-id",
          label: "Get user groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/transfer-members-to",
          label: "Move group members",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-members-to",
          label: "Replace group members",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-members-to",
          label: "Add group members",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/remove-members-from",
          label: "Remove group members",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-manager",
          label: "Set a group manager",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Group / Rooms",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-groups-with-shared",
          label: "Gets groups with shared",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "People / Contacts",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-member-contacts",
          label: "Delete user contacts",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-member-contacts",
          label: "Set user contacts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-member-contacts",
          label: "Update user contacts",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / Password",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-user-password",
          label: "Change a user password",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-user-password",
          label: "Remind a user password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "People / Photos",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-member-photo-thumbnails",
          label: "Create photo thumbnails",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-member-photo",
          label: "Delete a user photo",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-member-photo",
          label: "Get a user photo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-member-photo",
          label: "Update a user photo",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-member-photo",
          label: "Upload a user photo",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "People / Profiles",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-notification-to-change",
          label: "Send a notification to change a phone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-member",
          label: "Add a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all",
          label: "Get profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/invite-users",
          label: "Invite users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/resend-user-invites",
          label: "Resend activation emails",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-member",
          label: "Delete a user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-by-id",
          label: "Get a profile by user name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-member",
          label: "Update a user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-profile",
          label: "Delete my profile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/self",
          label: "Get my profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-by-email",
          label: "Get a profile by user email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-email-change-instructions",
          label: "Send instructions to change email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/remove-users",
          label: "Delete users",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-member-culture",
          label: "Update user language",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / Quota",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-user-quota",
          label: "Change a user quota limit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-users-quota",
          label: "Reset a user quota limit",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / Search",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-accounts-entries-with-shared",
          label: "Gets accounts entries with shared",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-advanced",
          label: "Search users by status filter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-full-by-filter",
          label: "Search users and their information by extended filter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-people-search",
          label: "Search users (using query parameters)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-search",
          label: "Search users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-simple-by-filter",
          label: "Search users by extended filter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-users-with-room-shared",
          label: "Gets users with shared in room ID specified in request",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "People / Theme",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-theme",
          label: "Get portal theme",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/change-theme",
          label: "Change portal theme",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / Third-party accounts",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-auth-providers",
          label: "Get third-party accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/link-account",
          label: "Link a third-pary account",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/signup-account",
          label: "Create a third-pary account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/unlink-account",
          label: "Unlink a third-pary account",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "People / User data",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-reassign-progress",
          label: "Get the reassignment progress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-reassign",
          label: "Start the data reassignment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/terminate-reassign",
          label: "Terminate the data reassignment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-remove-progress",
          label: "Get the deletion progress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-instructions-to-delete",
          label: "Send the deletion instructions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-remove",
          label: "Start the data deletion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/terminate-remove",
          label: "Terminate the data deletion",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / User status",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-by-status",
          label: "Get profiles by status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-user-status",
          label: "Change a user status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-employee-activation-status",
          label: "Set an activation status to the users",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "People / User type",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-user-type",
          label: "Change a user type",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-is-authentificated",
          label: "Check authentication",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/authenticate-me",
          label: "Authenticate a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/authenticate-me-from-body-with-code",
          label: "Authenticate a user by code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/logout",
          label: "Log out",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/check-confirm",
          label: "Open confirmation email URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-mobile-phone",
          label: "Set a mobile phone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-sms-code",
          label: "Send SMS code",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Capabilities",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-portal-capabilities",
          label: "Get portal capabilities",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Migration",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/list",
          label: "Gets migration list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-and-init",
          label: "Uploads and inits migration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/status",
          label: "Gets migration status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/cancel",
          label: "Cancels migration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/clear",
          label: "Clears migration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/migrate",
          label: "Migrates",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/logs",
          label: "Gets migration logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/finish",
          label: "Finishes migration",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Modules",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-1",
          label: "Get modules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-with-info",
          label: "Get modules information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Portal / Quota",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-used-space",
          label: "Get the used portal space",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-tariff",
          label: "Get a portal tariff",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-quota",
          label: "Get a portal quota",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-right-quota",
          label: "Get the recommended quota",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Portal / Settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get",
          label: "Get a portal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-shorten-link",
          label: "Get a shortened link",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-full-absolute-path",
          label: "Get a path to the portal",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-suspend-instructions",
          label: "Send suspension instructions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/suspend-portal",
          label: "Deactivate a portal",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-delete-instructions",
          label: "Send removal instructions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-portal",
          label: "Delete a portal",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/continue-portal",
          label: "Restore a portal",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Portal / Users",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-user",
          label: "Get a user by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/ge-invite-link",
          label: "Get an invitation link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-users-count",
          label: "Get a number of portal users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/mark-present-as-readed",
          label: "Mark a gift message as read",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-congratulations",
          label: "Send congratulations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Security / Active connections",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-active-connections",
          label: "Get active connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/log-out-all-active-connections-change-password",
          label: "Log out and change password",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/log-out-all-active-connections-for-user",
          label: "Log out for the user by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/log-out-all-except-this-connection",
          label: "Log out from all connections",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/log-out-active-connection",
          label: "Log out from the connection",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Security / Audit trail data",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-last-audit-events",
          label: "Get audit trail data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-audit-events-by-filter",
          label: "Get filtered audit trail data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-types",
          label: "Get audit trail types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-mappers",
          label: "Get audit trail mappers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-audit-trail-report",
          label: "Generate the audit trail report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-audit-settings",
          label: "Get the audit trail settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-audit-settings",
          label: "Set the audit trail settings",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Security / CSP",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/csp",
          label: "csp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-csp",
          label: "Gets csp",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Security / Firebase",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/doc-register-pusn-notification-device",
          label: "Save the Documents Firebase device token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/subscribe-documents-push-notification",
          label: "Subscribe to Documents push notification",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Security / Login history",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-last-login-events",
          label: "Get login history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-login-events-by-filter",
          label: "Get filtered login events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-login-history-report",
          label: "Generate the login history report",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Security / SMTP settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-smtp-settings",
          label: "Get the SMTP settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-smtp-settings",
          label: "Save the SMTP settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-smtp-settings",
          label: "Reset the SMTP settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/test-smtp-settings",
          label: "Test the SMTP settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-smtp-operation-status",
          label: "Get the SMTP test process status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Authorization",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-auth-services",
          label: "Get the authorization services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-auth-keys",
          label: "Save the authorization keys",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Common settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-settings",
          label: "Get the portal settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-mail-domain-settings",
          label: "Save the mail domain settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-supported-cultures",
          label: "Get supported languages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-time-zones-async",
          label: "Get time zones",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-machine-name",
          label: "Get hostname",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-dns-settings",
          label: "Save the DNS settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-logo",
          label: "Get a portal logo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/complete-wizard",
          label: "Complete the Wizard settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-color-theme",
          label: "Get a color theme",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-color-theme",
          label: "Save a color theme",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-color-theme",
          label: "Delete a color theme",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/close-admin-helper",
          label: "Close the admin helper notification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-email-activation-settings",
          label: "Update the email activation settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-socket-settings",
          label: "Get the socket settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/payment-settings",
          label: "Get the payment settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Cookies",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-cookie-settings",
          label: "Get cookies lifetime",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-cookie-settings",
          label: "Update cookies lifetime",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Custom Navigation",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-custom-navigation-items",
          label: "Get the custom navigation items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-custom-navigation-item-sample",
          label: "Get a custom navigation item sample",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-custom-navigation-item",
          label: "Get a custom navigation item by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-custom-navigation-item",
          label: "Add a custom navigation item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-custom-navigation-item",
          label: "Delete a custom navigation item",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Encryption",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/start-storage-encryption",
          label: "Start the storage encryption process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-storage-encryption-progress",
          label: "Get the storage encryption progress",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Greeting settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-greeting-settings",
          label: "Get greeting settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-greeting-settings",
          label: "Save the greeting settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/is-default",
          label: "Check the default greeting settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/restore-greeting-settings",
          label: "Restore the greeting settings",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / IP restrictions",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-ip-restrictions",
          label: "Get the IP portal restrictions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-ip-restrictions",
          label: "Save the IP restrictions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/read-ip-restrictions-settings",
          label: "Get the IP restriction settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-ip-restrictions-settings",
          label: "Update the IP restriction settings",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / License",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/refresh-license",
          label: "Refresh the license",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/accept-license",
          label: "Activate a license",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/request-license",
          label: "Request a license",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/upload-license",
          label: "Upload a license",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Login settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-login-settings",
          label: "Update login settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-login-settings",
          label: "Get login settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Messages",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/enable-admin-message-settings",
          label: "Enable the administrator message settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-adm-mail",
          label: "Send a message to the administrator",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-join-invite-mail",
          label: "Sends an invitation email",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Notifications",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-notification-settings",
          label: "Check notification availability",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-settings",
          label: "Enable notifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-rooms-notification-settings",
          label: "Get room notification settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-rooms-notification-status",
          label: "Set room notification status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Owner",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/send-owner-change-instructions",
          label: "Send the owner change instructions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/owner",
          label: "Update the portal owner",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Quota",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-user-quota-settings",
          label: "Gets user quota",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-room-quota-settings",
          label: "Save the room quota settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-tenant-quota-settings",
          label: "Save the tenant quota settings",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Rebranding",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-white-label-settings",
          label: "Save the white label settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-white-label-settings-from-files",
          label: "Save the white label settings from files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-white-label-logos",
          label: "Get the white label logos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-is-default-white-label-logos",
          label: "Check the default white label logos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-white-label-logo-text",
          label: "Get the white label logo text",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/restore-white-label-options",
          label: "Restore the white label options",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-licensor-data",
          label: "Get the licensor data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-company-white-label-settings",
          label: "Save the company white label settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-company-white-label-settings",
          label: "Get the company white label settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-company-white-label-settings",
          label: "Delete the company white label settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-additional-white-label-settings",
          label: "Save the additional white label settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-additional-white-label-settings",
          label: "Get the additional white label settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-additional-white-label-settings",
          label: "Delete the additional white label settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-enable-whitelabel",
          label: "Check the white label availability",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Security",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-web-item-settings-security-info",
          label: "Get the security settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-web-item-security",
          label: "Set the module security settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-web-item-security-info",
          label: "Get the module availability",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-enabled-modules",
          label: "Get the enabled modules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-password-settings",
          label: "Get the password settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-password-settings",
          label: "Set the password settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-access-to-web-items",
          label: "Set the access settings to products",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-product-administrators",
          label: "Get the product administrators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/is-product-administrator",
          label: "Check a product administrator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/set-product-administrator",
          label: "Set a product administrator",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / SSO",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-sso-settings-v-2",
          label: "Get the SSO settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-sso-settings-v-2",
          label: "Save the SSO settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-sso-settings-v-2",
          label: "Reset the SSO settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-default-sso-settings-v-2",
          label: "Get the default SSO settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-sso-settings-v-2-constants",
          label: "Get the SSO settings constants",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Statistics",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-space-usage-statistics",
          label: "Get the space usage statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-visit-statistics",
          label: "Get the visit statistics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Storage",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-storages",
          label: "Get storages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-storage",
          label: "Update a storage",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-storage-to-default",
          label: "Reset the storage settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-storage-progress",
          label: "Get the storage progress",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-cdn-storages",
          label: "Get the CDN storages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-cdn",
          label: "Update the CDN storage",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/reset-cdn-to-default",
          label: "Reset the CDN storage settings",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-all-backup-storages",
          label: "Get the backup storages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-amazon-s-3-regions",
          label: "Get Amazon regions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Team templates",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/people-schemas",
          label: "Get team templates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-naming-settings",
          label: "Save the naming settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/save-custom-naming-settings",
          label: "Create a custom team template",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/people-schema",
          label: "Get a team template by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / TFA settings",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-tfa-settings",
          label: "Get the TFA settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-settings",
          label: "Update the TFA settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-validate-auth-code",
          label: "Validate the TFA code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-confirm-url",
          label: "Get confirmation email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-settings-link",
          label: "Get confirmation email for updating TFA settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-app-generate-setup-code",
          label: "Generate setup code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-app-get-codes",
          label: "Get the TFA codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-app-request-new-codes",
          label: "Update the TFA codes",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/tfa-app-new-app",
          label: "Unlink the TFA application",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Tips",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-tips-settings",
          label: "Update the tip settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-tips-subscription",
          label: "Update the tip subscription",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-tips-subscription",
          label: "Check the tip subscription",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Webhooks",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-tenant-webhooks",
          label: "Get webhooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/create-webhook",
          label: "Create a webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-webhook",
          label: "Update a webhook",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/remove-webhook",
          label: "Remove a webhook",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/disable-web-hook",
          label: "Disable a webhook",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-journal",
          label: "Get webhook logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/retry-webhook",
          label: "Retry a webhook",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/retry-webhooks",
          label: "Retry webhooks",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/settings",
          label: "Get webhook settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings / Webplugins",
      items: [
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/add-web-plugin-from-file",
          label: "Adds web plugins from file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-web-plugins",
          label: "Gets web plugins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/get-web-plugin",
          label: "Gets web plugins by name specified in request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/update-web-plugin",
          label: "Updates web plugins",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "openapi/docSpace/API Backend/Usage API/delete-web-plugin",
          label: "Deletes web plugins by name specified in request",
          className: "api-method delete",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
